# 你的网站名
site_name: MkDocs基于Material的模板网站

site_url: https://github.com/SakurajimaMaii/MkDocs-Material-Template/

repo_name: MkDocs-Material-Template
repo_url: https://github.com/SakurajimaMaii/MkDocs-Material-Template

edit_uri: blob/main/docs/

# 主题设置
theme:
  name: material
  language: zh
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: 暗色模式
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: 亮色模式
  features:
    # https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/?h=nav#navigation-tabs
    - navigation.tabs
    - navigation.tabs.sticky
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/?h=edit#code-actions
    - content.action.edit

# 版权
copyright: This website follows MIT

# 插件
plugins:
  - search:
      lang: ja
  - awesome-pages:
      strict: false

# LaTeX支持
markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.tilde
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.highlight:
      use_pygments: true
  - footnotes
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
